# Generated by Django 4.1 on 2022-08-31 13:46

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Admin user',
                'verbose_name_plural': 'Admin Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.account',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Organization Admin',
                'verbose_name_plural': 'Organization Admin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.account',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
